// examples/vue/App.vue
<script setup lang="ts">
import Modal from './Modal.vue'
import { onMounted, ref } from 'vue';
import './style.css'
import { createBlendy, Blendy } from '../../src';

const blendy = ref<Blendy | null>(null)
const showModal = ref(false)

onMounted(() => {
  blendy.value = createBlendy()
})
</script>

<template>
  <div>
    <Teleport to="body">
      <Modal v-if="showModal"
        @close="() => {
          blendy?.untoggle('example', () => {
            showModal = false
          })
        }"></Modal>
    </Teleport>
    <button class="button"
      data-blendy-from="example"
      @click="() => {
        showModal = true
        blendy?.toggle('example')
      }"><span>Open</span></button>
  </div>
</template>

// examples/svelte/App.svelte
<script lang="ts">
  import { createBlendy, type Blendy } from '../../src'
  import { onMount } from 'svelte'
  import './style.css'
  import Modal from './Modal.svelte'
  let blendy: Blendy | null = null
  let showModal = false

  onMount(() => {
    blendy = createBlendy()
  })
</script>

<div>
  {#if showModal}
    <div class="modal-container">
      <Modal
        onclose={() => {
          blendy?.untoggle('example', () => {
            showModal = false
          })
        }}
      ></Modal>
    </div>
  {/if}
  <button
    class="button"
    data-blendy-from="example"
    onclick={() => {
      showModal = true
      blendy?.toggle('example')
    }}><span>Open</span></button
  >
</div>
