// examples/vue/App.vue
<script setup lang="ts">
import Modal from './Modal.vue'
import { onMounted, ref } from 'vue';
import './style.css'
import { createBlendy, Blendy } from '../../src';

const blendy = ref<Blendy | null>(null)
const showModal = ref(false)

onMounted(() => {
  blendy.value = createBlendy()
})
</script>

<template>
  <div>
    <Teleport to="body">
      <Modal v-if="showModal"
        @close="() => {
          blendy?.untoggle('example', () => {
            showModal = false
          })
        }"></Modal>
    </Teleport>
    <button class="button"
      data-blendy-from="example"
      @click="() => {
        showModal = true
        blendy?.toggle('example')
      }"><span>Open</span></button>
  </div>
</template>

// examples/angular/src/app/app.component.ts
import { Component, signal } from '@angular/core';
import { createBlendy } from '../../../../src'
import { ModalComponent } from './modal/modal.component';

@Component({
  selector: 'app-root',
  imports: [
    ModalComponent
  ],
  template: `


    <app-modal [hidden]="!showModal()" (close)="close()"></app-modal>
    

    <button class="button" data-blendy-from="example" (click)="open()">
      <span>Open</span>
    </button>
  `,
  styles: [],
})
export class AppComponent {
  title = 'blendy-angular-example';
  readonly showModal = signal(false);

  private readonly blendy = createBlendy({ animation: 'spring' });
  open() {
    this.blendy.toggle('example', () => {
      this.showModal.set(true);
    })
  }

  close() {
    this.blendy.untoggle('example', () => {
      this.showModal.set(false);
    });
  }
}
